namespace CSharpDom
{
    public enum BinaryOperatorExpressionType
    {
        Add,
        AddAssign,
        Assign,
        BitwiseAnd,
        LogicalAnd,
        BitwiseAndAssign,
        Coalesce,
        Divide,
        DivideAssign,
        Equal,
        BitwiseExclusiveOr,
        BitwiseExclusiveOrAssign,
        GreaterThan,
        GreaterThanOrEqual,
        LeftShift,
        LeftShfitAssign,
        LessThan,
        LessThanOrEqual,
        Modulo,
        ModuloAssign,
        Multiply,
        MultiplyAssign,
        NotEqual,
        BitwiseOr,
        BitwiseOrAssign,
        LogicalOr,
        RightShift,
        RightShiftAssign,
        Subtract,
        SubtractAssign,
        TypeIs,
        TypeAs
    }
}
